### ISSUE TITLE
User Story 6: Appearance and usability

### ISSUE THREAD

**Issue by CharlesTack** [CharlesTack/js-quiz#6]
**User Story 6: Appearance and usability**:
As a regular quiz user I want to be presented with a single screen quiz which is familiar, intuitive and logical in layout to me so that I can easily operate the quiz and navigate the site.

**Acceptance Criteria:**
- [ ] The layout should be logical, familiar and intuitive
- [ ] The quiz function should be similar to other quiz sites
- [ ] The quiz should give UX feedback to highlight the button selected
- [ ] Feedback is given to the user via red/green colour indications on answer response to indicate correctness
- [ ] The user can track how many questions they have answered and how many they have left to answer
- [ ] A reset/retry button is present to allow the user to try again

**Tasks:**
- [ ] Use HTML, CSS and Bootstrap to create a page which is laid out in a logical manner
- [ ] Research other quiz sites and utilise similar layouts
- [ ] Use Javascript to give UX feedback on button hover and selection
- [ ] Code Javascript to provide red/green feedback on answers
- [ ] Code a question counter section
- [ ] Code a reset/retry button
