### ISSUE TITLE
User Story 7: Completion Modal

### ISSUE THREAD

**Issue by CharlesTack** [CharlesTack/js-quiz#7]
**User Story 7: Completion Modal**
As a regular user of quiz sites, I like to feel the satisfaction of being congratulated on completing quizzes so that I can increase my self-esteem.

**Acceptance Criteria:**
- [ ] The site should have a congratulations message which appears on completion of the quiz.
- [ ] The message shoud include the final score
- [ ] The message should include congratulations and thanks.

**Tasks:**
- [ ] Code a modal window which appears on submission of the last answer.
- [ ] Integrate final score and congratulations/thanks message into modal.
